fixes:
  - "::github.com/secretflow/scql/"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default